name: CI/CD for React App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  HARBOR_REGISTRY: harbor.cccr-opensource.com  # Harbor 레지스트리 주소를 여기에 입력하세요
  IMAGE_NAME: cccr-project/front-app  # 프로젝트 이름과 이미지 이름을 적절히 수정하세요

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
      actions: read
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

    - name: Build Docker image
      run: |
        docker build -t ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker tag ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Login to Harbor
      uses: docker/login-action@v2
      with:
        registry: ${{ env.HARBOR_REGISTRY }}
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Push Docker image to Harbor
      run: |
        docker push ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    # 여기에 추가적인 배포 단계를 포함할 수 있습니다 (예: Kubernetes 배포 등)