name: CI/CD for React App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  HARBOR_REGISTRY: harbor.cccr-opensource.com
  IMAGE_NAME: cccr-project/front-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Debug information
      run: |
        pwd
        ls -la
        echo $PATH

    - name: Install Dependencies
      run: npm ci

    - name: Update Browserslist
      run: npx update-browserslist-db@latest

    - name: Install Babel Plugin
      run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

    - name: Build React App
      env:
        CI: false
      run: npm run build

    - name: Build Docker image
      run: |
        docker build -t ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker tag ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Login to Harbor
      uses: docker/login-action@v2
      with:
        registry: ${{ env.HARBOR_REGISTRY }}
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Push Docker image to Harbor
      run: |
        docker push ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest